services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  scraper:
    container_name: seatgeek_scraper
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    command: ["python", "main.py"]
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

volumes:
  db_data:
